### ISSUE TITLE
Does anyone have some IPython Notebooks they could share using ckanclient?

### ISSUE THREAD

**Issue by rsignell-usgs** [okfn/ckanclient-deprecated#27]
Does anyone have some IPython Notebooks they could share using ckanclient?  My google search of "ckan ext:ipynb" didn't turn up anything except for a notebook I created to test the CKAN CSW service.

Thanks,
Rich

**Comment by rufuspollock** [comment]
@rsignell-usgs could you explain in a bit more detail what you need for the ipython notebook - do you mean a demo of a notebook that uses ckanclient to access data?

**Comment by rsignell-usgs** [comment]
@rgrp: Exactly.  I'm thinking something like this CSW demo notebook, but for the CKAN API:
http://nbviewer.ipython.org/urls/raw.github.com/rsignell-usgs/ipython-notebooks/master/CSW_Testing_ISO_Queryables.ipynb

**Comment by rsignell-usgs** [comment]
Okay, I guess that's a no.  ;-)
Any python examples of searching for records using keywords, data start and stop stop time, geographic bounding box, and serviceType (e.g. WMS)?

**Comment by rufuspollock** [comment]
@rsignell-usgs sorry for slow follow-up! Would suggest asking on ckan-discuss list - http://lists.okfn.org/mailman/listinfo/ckan-discuss

**Comment by rufuspollock** [comment]
@zephod I hear you are a dab hand with ipython notebooks. Would you have any relevant examples to share here?

**Comment by teajaymars** [comment]
I have done an open ETL pipeline as part of a viz project at http://data.gov.uk/data/viz/social-investment-and-foundations. So the ETL script is an iPython notebook linked from there.

You can see it starts off using ckanclient but doesn't get anywhere serious with it. But in this case, the advantage of iPython notebook was to be transparent about how official graphs are being cooked, rather than doing a tech demo of a library's capabilities. (Direct link http://nbviewer.ipython.org/gist/zephod/7708219)

**Comment by rsignell-usgs** [comment]
@zephod.  Nice example!
Also, thanks to help from "D Read" on stackexchange (http://opendata.stackexchange.com/questions/1286/catalog-data-gov-using-ckan-api-with-python-requests-package) I was able to get a IPython Notebook example going with keyword, geospatial, and data endpoint search terms:
https://www.wakari.io/sharing/bundle/rsignell/Testing%20CKAN%20API%20on%20data.gov
Shines a bright light on all the metadata work we need to do....
